---
- name: Install yum utils
  package:
    name: yum-utils
    state: present
- name: install openJDK 8
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
- name: download and extract
  unarchive:
    src: "{{ tomcat_binary_url }}"
    dest: "/opt/"
    remote_src: yes
  sudo: True
- name: start tomcat app on {{ansible_hostname}}
  service:
    name: tomcat8
    state: started
    enabled: yes