---
- name: Gather information from EC2
  action: ec2_facts
- name: Install yum utils
  package:
    name: yum-utils
    state: present
- name: install openJDK 8
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
- name: tomcat installation on {{ansible_hostname}}
  yum:
    name: tomcat:8.0.53
    state: latest
- name: start tomcat app on {{ansible_hostname}}
  service:
    name: tomcat:8.0.53
    state: started
    enabled: yes