---
- hosts: appserver
  become: yes
  tasks:
  - name: Install yum utils
    package:
      name:
        - yum-utils
  - name: install openJDK 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat 7
    yum:
      name: tomcat
      state: present
  - name: download jenkins war file to webapps
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.176.2/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
